import * as fs from 'node:fs';
import * as path from 'node:path';
import { CompositionManager } from './composition-manager';

/**
 * Generates a TypeScript file that imports and registers all compositions
 * This file is imported by Root.tsx to dynamically register compositions
 */
export function generateCompositionLoader(
	compositionManager: CompositionManager,
	projectRoot: string,
): void {
	const compositions = compositionManager.getAllCompositions();
	const loaderPath = path.join(projectRoot, 'ai-compositions-registry.tsx');

	const imports: string[] = [];
	const compositionElements: string[] = [];

	compositions.forEach((comp) => {
		// Import path relative to where this file is generated (example/src/)
		const importPath = `./ai-projects/${comp.filePath.replace('.tsx', '')}`;
		const importName = `Comp${comp.id.replace(/[^a-zA-Z0-9]/g, '_')}`;
		
		// Try to import AIGeneratedComponent, fallback to default export
		imports.push(
			`// @ts-expect-error - Dynamic import
const ${importName}Module = require('${importPath}');
const ${importName} = ${importName}Module.AIGeneratedComponent || ${importName}Module.default;`,
		);

		compositionElements.push(`			<Composition
				id="${comp.id}"
				component={${importName}}
				width={${comp.width}}
				height={${comp.height}}
				fps={${comp.fps}}
				durationInFrames={${comp.durationInFrames}}
			/>`);
	});

	const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated by the composition manager.
 * It registers all AI-generated compositions dynamically.
 */

import React from 'react';
import { Composition } from 'remotion';

${imports.join('\n')}

export const AIGeneratedCompositions: React.FC = () => {
	return (
		<>
${compositionElements.join('\n')}
		</>
	);
};
`;

	try {
		fs.writeFileSync(loaderPath, fileContent, 'utf-8');
		console.log(`✅ Generated composition loader with ${compositions.length} compositions`);
	} catch (error) {
		console.error('❌ Error generating composition loader:', error);
	}
}

